require: rubocop-rails

Metrics/LineLength:
  Max: 120
AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/*.rb'
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - lib/parser/LiveSplitCore.rb
    - bin/**/*
    - node_modules/**/*
    - config/routes.rb
Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods:
    - draw
    - namespace

Metrics/MethodLength:
  Max: 20
