LineLength:
  Max: 120
AllCops:
  Include:
    - '**/*.rb'
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - lib/parser/LiveSplitCore.rb
    - bin/**/*
    - node_modules/**/*
    - config/routes.rb
Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods:
    - draw
    - namespace

Rails:
  Enabled: true
