language: bash
sudo: required
services:
  - docker
before_install: # Update docker-compose; Travis's built-in one is old
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - docker-compose build
script:
  - docker-compose run -e RAILS_ENV=test web bundle exec rake db:migrate
  - docker-compose run -e RAILS_ENV=test web bundle exec rspec
