version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
