# This is the Dockerfile for production. You only need to touch this if you are actually deploying Splits I/O to
# production. If you're not, look at Dockerfile instead.

FROM ruby:2.5.1

# Setup for current nodejs
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

# Setup for yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -\
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn

RUN mkdir /app
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install -j "$(expr "$(getconf _NPROCESSORS_ONLN)" - 1)"
COPY package.json yarn.lock ./
RUN yarn install

# You don't need to change anything in this file by hand! Set the below env vars as desired in your host, then use
#   cat Dockerfile | envsubst > Dockerfile.tmp && mv -f Dockerfile.tmp Dockerfile
# to substitute your host env vars into this file. Do this at build-time on the production box.

COPY . /app
EXPOSE 3000
