source 'https://rubygems.org'
ruby '2.1.3'

group :development do
  gem 'awesome_print'
  gem 'rubocop', require: false
  gem 'sqlite3'
  gem 'byebug'
end

group :production do
  gem 'pg', '>= 0.17.1'
  gem 'rollbar'
end

gem 'babel_bridge',              '>= 0.5.3'
gem 'coffee-rails',              '>= 4.0.0'
gem 'devise',                    '>= 3.1.1'
gem 'figaro',                    '>= 1.0.0.rc1'
gem 'gon',                       '>= 5.1.2'
gem 'htmlentities',              '>= 4.3.1'
gem 'jbuilder',                  '>= 1.2'
gem 'jquery-rails',              '>= 3.0.4'
gem 'purecss-rails',             '>= 0.3.0'
gem 'rails',                     '>= 4.0.0'
gem 'rails_12factor',            '>= 0.0.2'
gem 'sass-rails',                '>= 4.0.0'
gem 'spinjs-rails',              '>= 1.4'
gem 'thin',                      '>= 1.6.3'
gem 'tipsy-rails',               '>= 0.1.4'
gem 'uglifier',                  '>= 1.3.0'
gem 'unicorn',                   '>= 4.8.3'
gem 'vanity'
gem 'versionomy',                '>= 0.4.4'
gem 'will_paginate',             '>= 3.0.7'
gem 'workless',                  '>= 1.2.3'
gem 'xml-simple',                '>= 1.1.3'
gem 'redis-rails'
gem 'redis-namespace'
gem 'flat-ui-rails'
gem 'bootstrap-sass'
gem 'slim-rails'
gem 'haml-rails'
gem 'active_model_serializers'
gem 'httparty'
gem 'delayed_job_active_record'
gem 'foreman'
gem 'has_secure_token'
gem 'moving_average'
