default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timout: 5000
  username: postgres
  host: db
  port: 5432

development: &development
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <% if Rails.root.join('tmp/profiling-dev.txt').exist? %>
    <<: *development
  <% else %>
    url: <%= ENV['DATABASE_URL'] %>
  <% end %>
