default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timout: 5000
  username: postgres
  host: db
  port: 5432

development: &development
  <<: *default
  database: app_development

profiling:
  <<: *development

test:
  <<: *default
  database: app_test

production:
  url: <%= ENV['DATABASE_URL'] %>
