export const chartOptions = {
  exporting: {
    chartOptions: {
      chart: {
        color: 'rgba(255,255,255,0.07)'
      },
      credits: {
        enabled: true,
        text: 'generated by Splits.io <3'
      },
      plotOptions: {
        series: {
          dataLabels: {
            enabled: true
          }
        }
      }
    },
    fallbackToExportServer: false
  }
}
